name: Linting

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  phpcs:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpcs:3.0
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist
      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=vendor/wp-coding-standards/wpcs --extensions=php --ignore=vendor/* ./
